Rails Practice/goalie-master/config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"

  resources :users, only: [:new, :create, :index] do
    resources :goals, only: [:index]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :goals, except: :index do
    member do
      post 'complete'
    end
  end

  resources :comments, only: [:create]
end

Rails Practice/goalie-master/app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :comment, :commentable_id, :commentable_type, presence: true

  belongs_to :commentable, polymorphic: true

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id
  )
end

Rails Practice/goalie-master/app/models/concerns/commentable.rb
module Commentable
  extend ActiveSupport::Concern

  included do
    has_many :comments, as: :commentable, dependent: :destroy
  end
end

Rails Practice/goalie-master/app/models/goal.rb
class Goal < ActiveRecord::Base
  include Commentable

  PRIVACY_TYPES = ["Public", "Private"]

  validates :title, :user_id, :privacy, presence: true
  validates :privacy, inclusion: PRIVACY_TYPES

  belongs_to :user

  def completed?
    self.completed
  end

  def toggle_completed
    self.completed = !self.completed
    self.save!
  end
end

Rails Practice/goalie-master/app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  include Commentable

  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  after_initialize :ensure_session_token

  attr_reader :password

  has_many :goals, dependent: :destroy

  has_many(
    :authored_comments,
    class_name: "Comment",
    foreign_key: :author_id
  )

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    return user if user.is_password?(password)
    nil

  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

end

Rails Practice/goalie-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :log_in!

  def current_user
    return nil unless session[:session_token]
    @cu ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
    redirect_to user_goals_url(user)
  end

end

Rails Practice/goalie-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @owner = params[:id_type].constantize.find(params[:owner_id])
    @comment = @owner.comments.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to(:back)
    else
      flash[:errors] = ["Comment cannot be blank!"]
      redirect_to(:back)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

Rails Practice/goalie-master/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to goal_url(@goal)
    else
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy!
    redirect_to user_goals_url(@goal.user_id)
  end

  def show
    @goal = Goal.includes(comments: :author).find(params[:id])
  end

  def index
    @user = User.includes(comments: :author).find(params[:user_id])
    @goals = @user.goals
  end

  def complete
    @goal = Goal.find(params[:id])
    @goal.toggle_completed
    render :show
  end

  private
  def goal_params
    params.require(:goal).permit(:title, :description, :privacy)
  end
end

Rails Practice/goalie-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      redirect_to user_goals_url(current_user)
    else
      render :new
    end
  end

  def create
    @user = User.find_by_credentials(params[:username], params[:password])
    if @user
      log_in!(@user)
    else
      flash.now[:errors] = ["Username/password was incorrect."]
      render :new
    end
  end

  def destroy
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

Rails Practice/goalie-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

Rails Practice/goalie-master/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
    HTML
  end

end

Rails Practice/goalie-master/app/helpers/comments_helper.rb
module CommentsHelper
end

Rails Practice/goalie-master/app/helpers/goals_helper.rb
module GoalsHelper
end

Rails Practice/goalie-master/app/helpers/sessions_helper.rb
module SessionsHelper
end

Rails Practice/goalie-master/app/helpers/users_helper.rb
module UsersHelper
end

Rails Practice/goalie-master/app/views/goals/_form.html.erb
<% action = (goal.persisted? ? goal_url(goal) : goals_url) %>
<% method = (goal.persisted? ? "PATCH" : "POST")  %>
<% submit_text = (goal.persisted? ? "Save Goal" : "Create Goal") %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= auth_token %>

  <label for="Title">Title</label>
  <input type="text" name="goal[title]" value="<%= goal.title %>" id="Title">
  <br>

  <label for="Description">Description</label><br>
  <textarea name="goal[description]" rows="8" cols="40" id="Description"><%= goal.description %></textarea>
  <br>

  <label for="Public">Public</label>
  <input type="radio" name="goal[privacy]"
    value="Public" id="Public"
    <%= "checked" if goal.privacy == "Public" %>>

  <label for="Private">Private</label>
  <input type="radio" name="goal[privacy]"
    value="Private" id="Private"
    <%= "checked" if goal.privacy == "Private" %>>
    <br>

  <input type="submit" value="<%= submit_text %>">
</form>

Rails Practice/goalie-master/app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<%= render "form", goal: @goal %>

Rails Practice/goalie-master/app/views/goals/index.html.erb
<div class="container-fluid">
  <div class="jumbotron">
    <h1><%= @user.username %>'s Goals</h1>
  </div>
</div>

<ul class="list-group">
  <% @goals.each do |goal| %>
    <% if goal.privacy == "Public" || (current_user && goal.user_id == current_user.id) %>
    <li class="list-group-item">
      <button type="button" class="btn btn-default btn-lg" aria-label="Left Align">
        <a href="<%= goal_url(goal) %>"><%= goal.title %></a>
        <% if goal.completed? %>
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        <% end %>
      </button>
    </li>
    <% end %>
  <% end %>
  <li class="list-group-item list-group-item-success">
    <% if logged_in? && @user == current_user %>
      <button type="button" class="btn btn-default btn-lg">
        <a href="<%= new_goal_url %>">Add a New Goal</a>
      </button>
    <% end %>
  </li>
</ul>

<br>

<%= render "comments/comment", replies: @user.comments %>

Rails Practice/goalie-master/app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render "form", goal: @goal %>

Rails Practice/goalie-master/app/views/goals/show.html.erb
<div class="row">
  <div class="col-xs-9 col-xs-offset-1">
    <h1><%= @goal.title %></h1>

    <pre><%= @goal.description %></pre>
  </div>
</div>

<div class="row">
  <div class="col-xs-9 col-xs-offset-1">
    <h3>Privacy: <%= @goal.privacy %></h3>

    <h3><%= @goal.completed? ? "Completed" : "Not Completed" %></h3>


    <% if logged_in? && @goal.user_id == current_user.id %>
      <form action="<%= edit_goal_url(@goal) %>" method="get">
        <button class="btn btn-default" type="submit">Edit Goal</button>
      </form>
      <form action="<%= goal_url(@goal) %>" method="post">
        <input type="hidden" name="_method" value="DELETE">
        <%= auth_token %>
        <button class="btn btn-default" type="submit">Delete Goal</button>
      </form>
      <% if !@goal.completed? %>
        <form action="<%= complete_goal_url(@goal) %>" method="post">
          <%= auth_token %>
          <button class="btn btn-default" type="submit">Complete Goal</button>
        </form>
      <% else %>
        <form action="<%= complete_goal_url(@goal) %>" method="post">
          <%= auth_token %>
          <button class="btn btn-default" type="submit">Uncomplete Goal</button>
        </form>
      <% end %>
    <% end %>
  </div>
</div>
<br>
<%= render "comments/comment", replies: @goal.comments %>

Rails Practice/goalie-master/app/views/users/_form.html.erb
<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label for="Username">Username</label>
  <input type="text" name="user[username]" value="<%= user.username %>" id="Username">

  <label for="Password">Password</label>
  <input type="password" name="user[password]" id="Password">

  <input type="submit" value="Sign Up">
</form>

Rails Practice/goalie-master/app/views/users/index.html.erb
<h1>All Users</h1>

<ul class="list-group">
  <% @users.each do |user| %>
    <li class="list-group-item">
      <a href="<%= user_goals_url(user) %>"><%= user.username %></a>
    </li>
  <% end %>
</ul>

Rails Practice/goalie-master/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user %>