Rails Practice/music_app-master/config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :show]

  resources :bands

  resources :bands, only: [:show] do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :edit, :show, :update, :destroy]

  resources :tracks, only: [:show]

  resources :notes, only: [:create, :destroy]
end

Rails Practice/music_app-master/app/models/album.rb
class Album < ActiveRecord::Base

  ALBUM_TYPES = %w(Studio Live)

  validates :name, :band_id, :album_type, presence: true
  validates :album_type, inclusion: ALBUM_TYPES

  belongs_to :band
  has_many :tracks, dependent: :destroy

end

Rails Practice/music_app-master/app/models/band.rb
class Band < ActiveRecord::Base

  validates :name, presence: true

  has_many :albums, dependent: :destroy

end

Rails Practice/music_app-master/app/models/note.rb
class Note < ActiveRecord::Base
  validates :user_id, :track_id, :content, presence: true

  belongs_to :user
  belongs_to :track
end

Rails Practice/music_app-master/app/models/track.rb
class Track < ActiveRecord::Base
  TRACK_TYPES = %w(Regular Bonus)

  validates :name, :album_id, :track_type, presence: true
  validates :track_type, inclusion: TRACK_TYPES

  belongs_to :album
  has_many :notes

end

Rails Practice/music_app-master/app/models/user.rb
require 'BCrypt'

class User < ActiveRecord::Base
  validates :email, :password_digest, :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  has_many :notes

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(@password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
  end
end

Rails Practice/music_app-master/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :must_be_logged_in

  def new
    @album = Album.new
    @album.band_id = params[:band_id]
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy!
    redirect_to(band_url(@album.band_id))
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  private
  def album_params
    params.require(:album).permit(:name, :band_id, :album_type)
  end
end

Rails Practice/music_app-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :login!, :logged_in?

  def current_user
    @cu ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @user.reset_session_token!
    session[:session_token] = @user.session_token
    redirect_to user_url(@user)
  end

  def logged_in?
    !!current_user
  end

  def must_be_logged_in
    unless logged_in?
      redirect_to new_session_url
    end
  end

end

Rails Practice/music_app-master/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :must_be_logged_in

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy!
    redirect_to bands_url
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

Rails Practice/music_app-master/app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save!
    redirect_to track_url(@note.track_id)
  end

  def destroy
    @note = Note.find(params[:id])
    if current_user == @note.user
      @note.destroy
      redirect_to track_url(@note.track_id)
    else
      render text: "403 FORBIDDEN"
  end

  private
  def note_params
    params.require(:note).permit(:content, :track_id)
  end
end

Rails Practice/music_app-master/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:email], user_params[:password])
    unless @user
      render :new
    else
      login!(@user)
    end
  end

  def destroy
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
    redirect_to new_session_url
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

Rails Practice/music_app-master/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :must_be_logged_in

  def new
    @track = Track.new
    @track.album_id = params[:album_id]
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      render :edit
    end
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to(album_url(@track.album_id))
  end

  private
  def track_params
    params.require(:track).permit(:name, :album_id, :track_type, :lyrics)
  end
end

Rails Practice/music_app-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

Rails Practice/music_app-master/app/helpers/albums_helper.rb
module AlbumsHelper
end

Rails Practice/music_app-master/app/helpers/application_helper.rb
module ApplicationHelper
  def add_auth_token
    <<-HTML.html_safe
      <pre><input type="hidden"
      name="authenticity_token"
      value="#{form_authenticity_token}"></pre>
    HTML
  end

  def display_errors(object)
    <<-HTML.html_safe
      <pre>#{h(object.errors.full_messages.join("\n"))}</pre>
    HTML
  end
end

Rails Practice/music_app-master/app/helpers/bands_helper.rb
module BandsHelper
end

Rails Practice/music_app-master/app/helpers/notes_helper.rb
module NotesHelper
end

Rails Practice/music_app-master/app/helpers/sessions_helper.rb
module SessionsHelper
end

Rails Practice/music_app-master/app/helpers/tracks_helper.rb
module TracksHelper

  def ugly_lyrics(lyrics)
    lyric_arr = lyrics.split("\n")
    lyric_arr.map!{ |lyric| "♫ #{h(lyric)}" }
    <<-HTML.html_safe
      <pre>#{lyric_arr.join("\n")}</pre>
    HTML
  end
end

Rails Practice/music_app-master/app/helpers/users_helper.rb
module UsersHelper
end

Rails Practice/music_app-master/app/views/albums/_form.html.erb
<%= display_errors(@album) %>

<% @album.persisted? ? action = album_url(@album) : action = albums_url %>
<% @album.persisted? ? method = :put : :post %>
<% @album.persisted? ? submit_text = "Update Album" : submit_text = "Add Album" %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <%= add_auth_token %>

  <label for="name">Name</label>
  <input type="text" name="album[name]" value="<%= @album.name %>" id="name">
  <br>

  <label for="band_id">Band</label>
  <select id="band_id" name="album[band_id]">
    <% Band.all.each do |band| %>
    <option value="<%= band.id %>"
      <%= "selected" if band.id == @album.band_id %>>
      <%= band.name %>
    </option>
    <% end %>
  </select>
  <br>

  <label for="type_studio">Studio</label>
  <input type="radio"
    name="album[album_type]"
    value="Studio"
    id="type_studio"
    <%= "checked" if @album.album_type == "Studio" %>>
  <label for="type_live">Live</label>
  <input type="radio"
    name="album[album_type]"
    value="Live"
    id="type_live"
    <%= "checked" if @album.album_type == "Live" %>>
  <br>

  <input type="submit" value="<%= submit_text %>">

</form>

Rails Practice/music_app-master/app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form" %>

Rails Practice/music_app-master/app/views/albums/new.html.erb
<h1>Add A New Album</h1>

<%= render "form" %>

Rails Practice/music_app-master/app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<h2>by <%= @album.band.name %>

<h3>Tracks</h3>
<ol>
  <% @album.tracks.each do |track| %>
    <li><a href="<%= track_url(track) %>"><%= track.name %></a></li>
  <% end %>
</ol>

<a href="<%= new_album_track_url(@album.id) %>">Add Track</a>

<%= button_to "Edit Album", edit_album_url(@album), method: :get %>
<%= button_to "Delete Album", album_url(@album), method: :delete %>

<a href="<%= band_url(@album.band_id) %>">Back to Band</a>

Rails Practice/music_app-master/app/views/notes/_form.html.erb
<form action="<%= notes_url %>" method="post">

  <%= add_auth_token %>

  <input type="hidden" name="_method" value="POST">
  <textarea name="note[content]" rows="8" cols="40"></textarea><br>
  <input type="hidden" name="note[track_id]" value="<%= @track.id %>">

  <input type="submit" value="Create Note">
</form>

Rails Practice/music_app-master/app/views/notes/_note.html.erb
<% @track.notes.reverse.each do |note| %>
  <p><%= note.content  %></p>
  <h8>Written By <%= note.user.email %></h8>
  <% if current_user == note.user %>
    <%= button_to "Delete Note", note_url(note), method: :delete  %>
  <% end %>
<% end %>