Rails Practice/reddit_clone-master/config/routes.rb
Rails.application.routes.draw do
  root to: "subs#index"

  resources :users, only: [:new,:create]
  resources :subs, except: [:destroy]

  resources :posts, except: [:index, :destroy] do
    resources :comments, only: [:new]
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :comments, only: [:create, :show] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resource :session, only: [:new,:create,:destroy]

end

Rails Practice/reddit_clone-master/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true

  belongs_to(:post)

  belongs_to(
  :author,
  class_name: "User",
  foreign_key: :author_id)

  belongs_to(
    :parent_comment,
    class_name: "Comment",
    foreign_key: :parent_comment_id
  )

  has_many(
    :children_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id
  )

  has_many :votes, as: :votable

end

Rails Practice/reddit_clone-master/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:notices] = @comment.errors.full_messages
      @post = Post.find(params[:comment][:post_id])
      render :new
    end
  end

  def show
    @parent_comment = Comment.find(params[:id])
  end

  def upvote
    @comment = Comment.find(params[:id])
    @comment.votes.new(value: 1).save
    redirect_to comment_url(@comment)
  end

  def downvote
    @comment = Comment.find(params[:id])
    @comment.votes.new(value: -1).save
    redirect_to comment_url(@comment)
  end

  private
  def comment_params
    params.require(:comment).permit(:post_id,:parent_comment_id,:content)
  end
end

Rails Practice/reddit_clone-master/app/helpers/comments_helper.rb
module CommentsHelper
end

Rails Practice/reddit_clone-master/app/views/comments/_comment.html.erb
<p>
  Posted by: <%= comment.author.user_name %>
  <br>
  <%= comment.content %>
  <br>
  <a href="<%= comment_url(comment) %>">Click to show comment</a>
</p>

<% unless comment.children_comments.empty? %>
  <ul>
    <% all_comments[comment.id].each do |child| %>
      <li>
        <%= render "comments/comment", comment: child, all_comments: all_comments %>
        <form action="upvote_comment_url" method="post">
          <%= auth_token %>
          <input type="submit" value="▲">
        </form>
        <form action="downvote_comment_url" method="post">
          <%= auth_token %>
          <input type="submit" value="▼">
        </form>
      </li>
    <% end %>
  </ul>
<% end %>

Rails Practice/reddit_clone-master/app/views/comments/new.html.erb
<h1>Create Comment for <%= @post.title %></h1>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <textarea name="comment[content]" rows="8" cols="40"><%= @comment.content %></textarea>
  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
  <input type="submit" value="Create Comment">
</form>

Rails Practice/reddit_clone-master/app/views/comments/show.html.erb
<p>
  <%= @parent_comment.content %>
</p>
<form action="upvote_comment_url" method="post">
  <%= auth_token %>
  <input type="submit" value="▲">
</form>
<form action="downvote_comment_url" method="post">
  <%= auth_token %>
  <input type="submit" value="▼">
</form>

<form action="<%= comments_url %>" method="post">
  <%= auth_token %>
  <textarea name="comment[content]" rows="8" cols="40"></textarea>
  <input type="hidden" name="comment[post_id]" value="<%= @parent_comment.post.id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @parent_comment.id %>">
  <input type="submit" value="Create Comment">
</form>